package gogenerator

import (
	"bytes"
	"context"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"path/filepath"
	"sort"
	"strings"

	"github.com/dagger/go-sdk/cmd/dagger-go-sdk-codegen/generator"
	"github.com/dagger/go-sdk/cmd/dagger-go-sdk-codegen/introspection"
	"github.com/psanford/memfs"
	"golang.org/x/tools/imports"
)

// GenerateUnifiedClient emits module bindings that reuse core's Go types.
// The generated root owns no engine lifecycle and exposes only module fields.
func (g *GoGenerator) GenerateUnifiedClient(ctx context.Context, schema *introspection.Schema, schemaVersion string) (*generator.GeneratedState, error) {
	generator.SetSchemaParents(schema)
	generator.SetSchema(schema)
	if g.Config.PackageImport == "" {
		return nil, fmt.Errorf("package import path is required")
	}
	name := g.Config.PackageName
	if name == "" {
		name = clientPackageName(filepath.Base(g.Config.PackageImport))
	}
	pkg := &PackageInfo{PackageName: name, PackageImport: g.Config.PackageImport}
	mfs := memfs.New()
	if err := generateDependencyFiles(ctx, g.Config, schema, schemaVersion, mfs, pkg, schema.DependencyNames()); err != nil {
		return nil, err
	}
	var bound generator.BoundModule
	if g.Config.ClientConfig != nil {
		bound = g.Config.ClientConfig.BoundModule
	}
	address := bound.Ref
	if bound.Kind != generator.ModuleKindGit {
		address = bound.Path
		if address != "" && !strings.HasPrefix(address, "/") {
			address = "/" + address
		}
	}
	// Add aliases only for core types referenced by module bindings. They retain
	// type identity across generated clients and dagger.io/dagger/core.
	referenced := map[string]bool{"ID": true, "Node": true}
	coreNames := map[string]bool{}
	for _, typ := range schema.Types {
		if typ.Name == "Query" || typ.Directives.SourceMap() != nil {
			continue
		}
		if typ.Kind == introspection.TypeKindScalar && (typ.Name == "String" || typ.Name == "Int" || typ.Name == "Float" || typ.Name == "Boolean") {
			continue
		}
		coreNames[typ.Name] = true
		if typ.Kind == introspection.TypeKindInterface {
			coreNames[typ.Name+"Client"] = true
		}
	}
	files, err := fs.ReadDir(mfs, ".")
	if err != nil {
		return nil, err
	}
	for _, file := range files {
		data, err := fs.ReadFile(mfs, file.Name())
		if err != nil {
			return nil, err
		}
		parsed, err := parser.ParseFile(token.NewFileSet(), file.Name(), data, 0)
		if err != nil {
			return nil, err
		}
		ast.Inspect(parsed, func(n ast.Node) bool {
			if id, ok := n.(*ast.Ident); ok && coreNames[id.Name] {
				referenced[id.Name] = true
			}
			return true
		})
	}
	var aliases bytes.Buffer
	names := make([]string, 0, len(referenced))
	for n := range referenced {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		target := n
		if n != "ID" && strings.HasSuffix(n, "ID") {
			target = "ID"
		}
		fmt.Fprintf(&aliases, "type %s = core.%s\n", n, target)
	}
	transport := fmt.Sprintf("dagger.ModuleGraphQLClient(connection, %q, %q)", address, bound.Pin)
	if address == "" {
		transport = "defaultOrExplicit(connection)"
	}
	embeddedCore, initQuery := "", "&Query{query:q}"
	if g.Config.ModuleConfig != nil {
		embeddedCore = "; *core.Query"
		initQuery = "&Query{query:q,Query:new(core.Query).WithGraphQLQuery(q)}"
	}
	source := fmt.Sprintf(`// Code generated by dagger. DO NOT EDIT.
package %s
import (
 "context"
 "encoding/json"
 "fmt"
 "reflect"
 "dagger.io/dagger"
 "dagger.io/dagger/core"
 "github.com/dagger/querybuilder"
 "github.com/Khan/genqlient/graphql"
)
%s
// Client borrows a shared connection. Its API contains only the bound module.
type Client struct { *Query }
type Query struct { query *querybuilder.Selection %s }
type DaggerObject = core.DaggerObject
type ExecError = dagger.ExecError
var marshalCtx = context.Background()
func SetMarshalContext(ctx context.Context) {marshalCtx=ctx;core.SetMarshalContext(ctx)}
// Connect is retained for module dispatchers generated before New was introduced.
func Connect() *Client {return New()}
// New constructs lazy bindings. An omitted connection uses the shared session.
func New(connections ...*dagger.Client) *Client {
 if len(connections)>1 {panic("New accepts at most one connection")}
 var connection *dagger.Client
 if len(connections)==1 {connection=connections[0]}
 q := querybuilder.Query().Client(%s)
 return &Client{Query:%s}
}
func defaultOrExplicit(client *dagger.Client) graphql.Client {
 if client==nil{return dagger.DefaultGraphQLClient()};return client.GraphQLClient()
}
func (c *Client) QueryBuilder() *querybuilder.Selection {return c.query}
func selectNode(q *querybuilder.Selection,id any,name string)*querybuilder.Selection{return q.Select("node").Arg("id",id).InlineFragment(name)}
func assertNotNil(name string,value any){if reflect.ValueOf(value).IsNil(){panic(fmt.Sprintf("unexpected nil pointer for argument %%q",name))}}
func Ref[T core.Loadable[T]](client *Client,id core.ID)T{return core.Ref[T](new(core.Query).WithGraphQLQuery(client.query),id)}
func Load[T core.Loadable[T]](ctx context.Context,client *Client,id core.ID)(T,error){return core.Load[T](ctx,new(core.Query).WithGraphQLQuery(client.query),id)}
`, name, aliases.String(), embeddedCore, transport, initQuery)
	formatted, err := imports.Process(filepath.Join(g.Config.OutputDir, "dagger.gen.go"), []byte(source), nil)
	if err != nil {
		return nil, err
	}
	if err = mfs.WriteFile("dagger.gen.go", formatted, 0644); err != nil {
		return nil, err
	}
	return &generator.GeneratedState{Overlay: mfs}, nil
}

func clientPackageName(value string) string {
	var b strings.Builder
	for _, r := range value {
		if r == '_' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' {
			b.WriteRune(r)
		}
	}
	name := b.String()
	if name == "" || name[0] >= '0' && name[0] <= '9' || token.IsKeyword(name) {
		return "client"
	}
	return name
}
