package main

import "fmt"

type TomlGenerateApp struct{}

// Greet someone.
func (m *TomlGenerateApp) Greeting(name string) string {
	return fmt.Sprintf("hello %s, generated by the go-sdk codegen", name)
}
