package generator

import (
	"os"
	"path/filepath"
	"testing"
	"testing/fstest"

	"github.com/stretchr/testify/require"
)

func ownedFixture(files map[string]string) fstest.MapFS {
	result := fstest.MapFS{}
	for path, value := range files {
		result[path] = &fstest.MapFile{Data: []byte("// Code generated by dagger. DO NOT EDIT.\n" + value)}
	}
	return result
}

func TestOwnershipRegenerationAndRemoval(t *testing.T) {
	root := t.TempDir()
	_, err := WriteOwnedOverlay(t.Context(), ownedFixture(map[string]string{"a.gen.go": "old", "nested/b.gen.go": "old"}), root)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(filepath.Join(root, "README.md"), []byte("author notes"), 0644))
	removed, err := WriteOwnedOverlay(t.Context(), ownedFixture(map[string]string{"a.gen.go": "new"}), root)
	require.NoError(t, err)
	require.Equal(t, []string{"nested/b.gen.go"}, removed)
	require.NoError(t, PruneOwnedClient(t.Context(), root))
	_, err = os.Stat(filepath.Join(root, "a.gen.go"))
	require.ErrorIs(t, err, os.ErrNotExist)
	data, err := os.ReadFile(filepath.Join(root, "README.md"))
	require.NoError(t, err)
	require.Equal(t, "author notes", string(data))
}

func TestOwnershipChecksAllCollisionsBeforeWriting(t *testing.T) {
	root := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(root, "z.gen.go"), []byte("author code"), 0644))
	_, err := WriteOwnedOverlay(t.Context(), ownedFixture(map[string]string{"a.gen.go": "new", "z.gen.go": "new"}), root)
	require.ErrorContains(t, err, "user changes")
	_, err = os.Stat(filepath.Join(root, "a.gen.go"))
	require.ErrorIs(t, err, os.ErrNotExist)
	_, err = os.Stat(filepath.Join(root, OwnershipFile))
	require.ErrorIs(t, err, os.ErrNotExist)
}

func TestOwnershipCollisionPreservesCompatibilityChoice(t *testing.T) {
	root := t.TempDir()
	enabled := false
	_, err := WriteOwnedOverlayWithCompatibility(t.Context(), ownedFixture(map[string]string{"a.gen.go": "old"}), root, Compatibility{GlobalClient: &enabled})
	require.NoError(t, err)
	before, err := os.ReadFile(filepath.Join(root, OwnershipFile))
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(filepath.Join(root, "z.gen.go"), []byte("author code"), 0644))
	enabled = true
	_, err = WriteOwnedOverlayWithCompatibility(t.Context(), ownedFixture(map[string]string{"a.gen.go": "new", "z.gen.go": "new"}), root, Compatibility{GlobalClient: &enabled})
	require.ErrorContains(t, err, "user changes")
	after, err := os.ReadFile(filepath.Join(root, OwnershipFile))
	require.NoError(t, err)
	require.Equal(t, before, after)
	generated, err := os.ReadFile(filepath.Join(root, "a.gen.go"))
	require.NoError(t, err)
	require.Contains(t, string(generated), "old")
}

func TestOwnershipPreservesEditedGeneratedFiles(t *testing.T) {
	root := t.TempDir()
	_, err := WriteOwnedOverlay(t.Context(), ownedFixture(map[string]string{"a.gen.go": "old"}), root)
	require.NoError(t, err)
	edited := "// Code generated by dagger. DO NOT EDIT.\nuser edit"
	require.NoError(t, os.WriteFile(filepath.Join(root, "a.gen.go"), []byte(edited), 0644))
	_, err = WriteOwnedOverlay(t.Context(), ownedFixture(map[string]string{"a.gen.go": "new"}), root)
	require.ErrorContains(t, err, "user changes")
	require.NoError(t, PruneOwnedClient(t.Context(), root))
	data, err := os.ReadFile(filepath.Join(root, "a.gen.go"))
	require.NoError(t, err)
	require.Equal(t, edited, string(data))
}

func TestOwnershipRejectsEscapingPaths(t *testing.T) {
	t.Run("manifest", func(t *testing.T) {
		root := t.TempDir()
		require.NoError(t, os.WriteFile(filepath.Join(root, OwnershipFile), []byte(`{"version":1,"files":{"../author.go":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}}`), 0644))
		require.ErrorContains(t, PruneOwnedClient(t.Context(), root), "invalid generated ownership")
	})
	t.Run("symlink", func(t *testing.T) {
		root := t.TempDir()
		require.NoError(t, os.Symlink(t.TempDir(), filepath.Join(root, "nested")))
		_, err := WriteOwnedOverlay(t.Context(), ownedFixture(map[string]string{"nested/a.gen.go": "new"}), root)
		require.ErrorContains(t, err, "symlink")
	})
}
