package generator

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/psanford/memfs"
)

const OwnershipFile = ".dagger-generated.json"

type Ownership struct {
	Version       int               `json:"version"`
	Files         map[string]string `json:"files"`
	Compatibility *Compatibility    `json:"compatibility,omitempty"`
}

// Compatibility records migration choices independently of the generated
// source layout. A scope setting supplied by the user still overrides them.
type Compatibility struct {
	GlobalClient *bool `json:"globalClient,omitempty"`
}

func digest(data []byte) string { sum := sha256.Sum256(data); return hex.EncodeToString(sum[:]) }
func generated(data []byte) bool {
	return bytes.HasPrefix(data, []byte("// Code generated by dagger.")) || bytes.HasPrefix(data, []byte("# Code generated by dagger."))
}

// WriteOwnedOverlay validates every collision before writing and prunes only
// files that still match the generator's recorded content. User files survive.
func WriteOwnedOverlay(ctx context.Context, overlay fs.FS, root string) ([]string, error) {
	return ownedOverlay(ctx, overlay, root, true, nil)
}

// WriteOwnedOverlayWithCompatibility persists a module's resolved migration
// mode together with its successfully generated and collision-checked files.
func WriteOwnedOverlayWithCompatibility(ctx context.Context, overlay fs.FS, root string, compatibility Compatibility) ([]string, error) {
	return ownedOverlay(ctx, overlay, root, true, &compatibility)
}

// ValidateOwnedOverlay checks all paths before callers update other files.
func ValidateOwnedOverlay(ctx context.Context, overlay fs.FS, root string) error {
	_, err := ownedOverlay(ctx, overlay, root, false, nil)
	return err
}

func ownedOverlay(ctx context.Context, overlay fs.FS, root string, write bool, compatibility *Compatibility) ([]string, error) {
	if err := checkOwnedParents(root, OwnershipFile); err != nil {
		return nil, err
	}
	old, err := ReadOwnership(root)
	if err != nil {
		return nil, err
	}
	next := Ownership{Version: 1, Files: map[string]string{}, Compatibility: old.Compatibility}
	if compatibility != nil {
		next.Compatibility = compatibility
	}
	dataByPath := map[string][]byte{}
	err = fs.WalkDir(overlay, ".", func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		if !fs.ValidPath(path) || path == OwnershipFile {
			return fmt.Errorf("invalid generated path %q", path)
		}
		if err = ctx.Err(); err != nil {
			return err
		}
		if err = checkOwnedParents(root, path); err != nil {
			return err
		}
		data, err := fs.ReadFile(overlay, path)
		if err != nil {
			return err
		}
		existing, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(path)))
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		if err == nil && !bytes.Equal(existing, data) {
			hash, owned := old.Files[path]
			if !generated(existing) || owned && hash != digest(existing) {
				return fmt.Errorf("%s contains user changes; refusing to overwrite it", path)
			}
		}
		next.Files[path] = digest(data)
		dataByPath[path] = data
		return nil
	})
	if err != nil {
		return nil, err
	}
	var removed []string
	for path, hash := range old.Files {
		if _, ok := next.Files[path]; ok {
			continue
		}
		if err = checkOwnedParents(root, path); err != nil {
			return nil, err
		}
		data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(path)))
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return nil, err
		}
		if generated(data) && digest(data) == hash {
			removed = append(removed, path)
		}
	}
	paths := make([]string, 0, len(dataByPath))
	for path := range dataByPath {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	sort.Strings(removed)
	if !write {
		return removed, nil
	}
	for _, path := range paths {
		full := filepath.Join(root, filepath.FromSlash(path))
		if err = os.MkdirAll(filepath.Dir(full), 0755); err != nil {
			return nil, err
		}
		if err = os.WriteFile(full, dataByPath[path], 0644); err != nil {
			return nil, err
		}
	}
	for _, path := range removed {
		if err = os.Remove(filepath.Join(root, filepath.FromSlash(path))); err != nil {
			return nil, err
		}
	}
	data, err := json.MarshalIndent(next, "", "  ")
	if err != nil {
		return nil, err
	}
	data = append(data, '\n')
	if err = os.MkdirAll(root, 0755); err != nil {
		return nil, err
	}
	if err = os.WriteFile(filepath.Join(root, OwnershipFile), data, 0644); err != nil {
		return nil, err
	}
	return removed, nil
}

func ReadOwnership(root string) (Ownership, error) {
	manifest := Ownership{Version: 1, Files: map[string]string{}}
	data, err := os.ReadFile(filepath.Join(root, OwnershipFile))
	if errors.Is(err, os.ErrNotExist) {
		return manifest, nil
	}
	if err != nil {
		return manifest, err
	}
	if err = json.Unmarshal(data, &manifest); err != nil {
		return manifest, fmt.Errorf("read generated ownership: %w", err)
	}
	if manifest.Version != 1 {
		return manifest, fmt.Errorf("unsupported generated ownership version %d", manifest.Version)
	}
	for path, hash := range manifest.Files {
		_, hashErr := hex.DecodeString(hash)
		if !fs.ValidPath(path) || path == "." || path == OwnershipFile || strings.Contains(path, "\\") || len(hash) != 64 || hashErr != nil {
			return manifest, fmt.Errorf("invalid generated ownership entry %q", path)
		}
	}
	return manifest, nil
}

func checkOwnedParents(root, path string) error {
	for dir := filepath.Clean(root); ; dir = filepath.Dir(dir) {
		info, err := os.Lstat(dir)
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		if err == nil && info.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("generated root %s crosses a symlink", root)
		}
		if filepath.Dir(dir) == dir {
			break
		}
	}
	parts := strings.Split(path, "/")
	full := root
	for _, part := range parts {
		full = filepath.Join(full, part)
		info, err := os.Lstat(full)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return err
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("generated path %s crosses a symlink", path)
		}
	}
	return nil
}

// PruneOwnedClient removes only unchanged generated files for a removed client.
func PruneOwnedClient(ctx context.Context, root string) error {
	_, err := WriteOwnedOverlay(ctx, memfs.New(), root)
	return err
}
