package gogenerator

import (
	"bytes"
	"context"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	clientgen "github.com/dagger/go-sdk/cmd/dagger-go-sdk-codegen/generator/gogenerator"
)

// collectionBuildSources rewrites a temporary build copy. Author files remain
// untouched, while copied collection values retain the engine's private base.
func collectionBuildSources(ctx context.Context, root string) (map[string][]byte, error) {
	paths, err := filepath.Glob(filepath.Join(root, "*.go"))
	if err != nil {
		return nil, err
	}
	needed := false
	for _, path := range paths {
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		if bytes.Contains(data, []byte("+collection")) {
			needed = true
		}
	}
	if !needed {
		return nil, nil
	}
	dir, err := os.MkdirTemp("", "go-collection-build-")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(dir)
	if err = os.CopyFS(dir, os.DirFS(root)); err != nil {
		return nil, fmt.Errorf("copy collection build source: %w", err)
	}
	if err = ctx.Err(); err != nil {
		return nil, err
	}
	if err = clientgen.PrepareCollectionRuntime(dir); err != nil {
		return nil, err
	}
	result := map[string][]byte{}
	for _, path := range paths {
		name := filepath.Base(path)
		old, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return nil, err
		}
		if !bytes.Equal(old, data) {
			result[name] = data
		}
	}
	return result, nil
}

func writeCollectionBuild(root string, entrypoint []byte, files map[string][]byte) ([]byte, error) {
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	var source strings.Builder
	source.WriteString("let source = currentModule.source")
	for _, name := range names {
		if !fs.ValidPath(name) || filepath.Base(name) != name {
			return nil, fmt.Errorf("invalid runtime source path %q", name)
		}
		rel := "internal/dagger/entrypoint/runtime/" + name + ".src"
		if err := checkGeneratedPath(root, filepath.Join(root, rel)); err != nil {
			return nil, err
		}
		data := append([]byte("// Code generated by dagger. DO NOT EDIT.\n"), files[name]...)
		if err := writeFile(filepath.Join(root, rel), data); err != nil {
			return nil, err
		}
		fmt.Fprintf(&source, "\n      .withFile(%s, currentModule.source.file(%s))", strconv.Quote(name), strconv.Quote(rel))
	}
	return bytes.Replace(entrypoint, []byte("let source = currentModule.source"), []byte(source.String()), 1), nil
}
