package gogenerator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"testing/fstest"
)

func TestGenerateRefusesParentGoModuleBeforeWriting(t *testing.T) {
	parent := t.TempDir()
	writeTestFile(t, filepath.Join(parent, "go.mod"), "module example.com/project\n\ngo 1.26\n")
	root := filepath.Join(parent, "module")
	if err := os.MkdirAll(root, 0755); err != nil {
		t.Fatal(err)
	}
	writeTestFile(t, filepath.Join(root, "main.go"), "package main\n\ntype HelloWorld struct{}\n")
	err := Generate(t.Context(), GenerateConfig{ModuleRoot: root, ModuleName: "hello-world"})
	if err == nil || !strings.Contains(err.Error(), "parent go.mod") {
		t.Fatalf("Generate() error = %v", err)
	}
	entries, err := os.ReadDir(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 1 || entries[0].Name() != "main.go" {
		t.Errorf("a refused module changed: %v", entries)
	}
}

func TestGenerateRefusesToOverwriteUserFiles(t *testing.T) {
	for _, rel := range []string{
		"cmd/hello-world-dispatch/main.go",
		"internal/dagger/entrypoint/main.dang",
		"dagger.gen.go",
	} {
		t.Run(rel, func(t *testing.T) {
			root := t.TempDir()
			writeTestFile(t, filepath.Join(root, "main.go"), "package hello_world\n\ntype HelloWorld struct{}\n")
			userFile := filepath.Join(root, filepath.FromSlash(rel))
			if err := os.MkdirAll(filepath.Dir(userFile), 0o755); err != nil {
				t.Fatal(err)
			}
			writeTestFile(t, userFile, "user code\n")

			err := Generate(t.Context(), GenerateConfig{ModuleRoot: root, ModuleName: "hello-world"})
			if err == nil || !strings.Contains(err.Error(), rel+" exists and is not generated code") {
				t.Fatalf("Generate() error = %v, want a collision error for %s", err, rel)
			}
			data, err := os.ReadFile(userFile)
			if err != nil {
				t.Fatal(err)
			}
			if string(data) != "user code\n" {
				t.Errorf("%s was overwritten: %q", rel, data)
			}
			if _, err := os.Stat(filepath.Join(root, "go.mod")); err == nil {
				t.Error("go.mod was created before the collision was reported")
			}
		})
	}
}

func TestCheckGeneratedPathAcceptsGeneratedFiles(t *testing.T) {
	root := t.TempDir()
	for name, contents := range map[string]string{
		"main.go":   "// Code generated by dagger. DO NOT EDIT.\n\npackage main\n",
		"main.dang": "# Code generated by dagger. Do not edit.\n\ntype Entrypoint {}\n",
	} {
		path := filepath.Join(root, name)
		writeTestFile(t, path, contents)
		if err := checkGeneratedPath(root, path); err != nil {
			t.Errorf("checkGeneratedPath(%s) = %v", name, err)
		}
	}
	if err := checkGeneratedPath(root, filepath.Join(root, "missing.go")); err != nil {
		t.Errorf("checkGeneratedPath(missing) = %v", err)
	}
}

func TestSourcePackageNameRejectsMixedPackages(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "a.go"), "package hello\n")
	writeTestFile(t, filepath.Join(root, "b.go"), "package other\n")

	if _, err := sourcePackageName(root); err == nil {
		t.Fatal("sourcePackageName() accepted two packages")
	}
}

func TestEnsureGoModuleUsesEnclosingModule(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "go.mod"), "module example.com/app\n\ngo 1.25\n")
	moduleRoot := filepath.Join(root, "mods", "hello")
	if err := os.MkdirAll(moduleRoot, 0o755); err != nil {
		t.Fatal(err)
	}

	packageImport, goModPath, err := ensureGoModule(moduleRoot, "hello")
	if err != nil {
		t.Fatal(err)
	}
	if packageImport != "example.com/app/mods/hello" {
		t.Errorf("package import = %q, want example.com/app/mods/hello", packageImport)
	}
	if goModPath != filepath.Join(root, "go.mod") {
		t.Errorf("go.mod path = %q, want the enclosing go.mod", goModPath)
	}
	if _, err := os.Stat(filepath.Join(moduleRoot, "go.mod")); err == nil {
		t.Error("a nested go.mod was created")
	}
}

func TestPinDaggerKeepsReplaceAndNewerVersion(t *testing.T) {
	for name, goMod := range map[string]string{
		"replace":        "module example.com/app\n\ngo 1.25\n\nreplace dagger.io/dagger => ../sdk\n",
		"newer required": "module example.com/app\n\ngo 1.25\n\nrequire dagger.io/dagger v1.0.0-beta.20\n",
	} {
		t.Run(name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "go.mod")
			writeTestFile(t, path, goMod)

			if err := pinDagger(path, "v1.0.0-beta.14"); err != nil {
				t.Fatal(err)
			}
			data, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			if string(data) != goMod {
				t.Errorf("go.mod changed:\n%s", data)
			}
		})
	}
}

func TestRemoveStaleBindingsReportsRemovedFiles(t *testing.T) {
	root := t.TempDir()
	dir := filepath.Join(root, "internal", "dagger")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	generated := "// Code generated by dagger. DO NOT EDIT.\n\npackage dagger\n"
	writeTestFile(t, filepath.Join(dir, "dagger.gen.go"), generated)
	writeTestFile(t, filepath.Join(dir, "kept.gen.go"), generated)
	writeTestFile(t, filepath.Join(dir, "stale.gen.go"), generated)
	writeTestFile(t, filepath.Join(dir, "user.gen.go"), "package dagger\n")
	overlay := fstest.MapFS{"internal/dagger/kept.gen.go": {Data: []byte(generated)}}

	removed, err := removeStaleBindings(root, overlay)
	if err != nil {
		t.Fatal(err)
	}
	if len(removed) != 1 || removed[0] != "internal/dagger/stale.gen.go" {
		t.Errorf("removed = %v, want [internal/dagger/stale.gen.go]", removed)
	}
	for name, want := range map[string]bool{"dagger.gen.go": true, "kept.gen.go": true, "stale.gen.go": false, "user.gen.go": true} {
		if _, err := os.Stat(filepath.Join(dir, name)); (err == nil) != want {
			t.Errorf("%s exists = %t, want %t", name, err == nil, want)
		}
	}
}

func writeTestFile(t *testing.T, path, contents string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatal(err)
	}
}
