package gogenerator

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dagger/go-sdk/cmd/dagger-go-sdk-codegen/generator"
	"github.com/stretchr/testify/require"
)

// This covers package loading, generated decoders, the static dispatcher, and
// repeated generation rather than only checking a template's text.
func TestGenerateGlobalClientModes(t *testing.T) {
	sdk := os.Getenv("GO_SDK_TEST_RUNTIME")
	if sdk == "" {
		t.Skip("set GO_SDK_TEST_RUNTIME to the SDK split checkout")
	}
	schema, err := filepath.Abs("../../../cmd/dagger-go-sdk-codegen/generator/gogenerator/testdata/core/schema.json")
	require.NoError(t, err)
	for _, test := range []struct {
		name     string
		enabled  bool
		embedded bool
	}{
		{name: "default"},
		{name: "default embedded", embedded: true},
		{name: "explicit compatibility", enabled: true},
		{name: "explicit embedded compatibility", enabled: true, embedded: true},
	} {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			mod := "module example.com/hello\n\ngo 1.26\n\nrequire dagger.io/dagger v1.0.0-beta.15\nreplace dagger.io/dagger => " + sdk + "\n"
			require.NoError(t, os.WriteFile(filepath.Join(root, "go.mod"), []byte(mod), 0644))
			source := `package hello
import (
 "context"
 "example.com/hello/internal/dagger"
)
type Hello struct{}
type Greeter interface {
 dagger.DaggerObject
 Greet(context.Context) (string, error)
}
func (h *Hello) Use(value Greeter) string { return "decoded interface" }
func (h *Hello) Echo(value *dagger.Container) string { return "decoded core object" }
`
			if test.enabled {
				source += "func (h *Hello) Legacy() *dagger.Container { return dag.Container() }\n"
			}
			require.NoError(t, os.WriteFile(filepath.Join(root, "main.go"), []byte(source), 0644))
			cfg := GenerateConfig{ModuleRoot: root, ModuleName: "hello", SchemaPath: schema, SchemaVersion: "v1.0.0-beta.15", UnifiedClient: !test.embedded, GoImage: "golang:1.26-alpine", GlobalClient: test.enabled}
			require.NoError(t, Generate(t.Context(), cfg))
			first, err := os.ReadFile(filepath.Join(root, "dagger.gen.go"))
			require.NoError(t, err)
			firstMod, err := os.ReadFile(filepath.Join(root, "go.mod"))
			require.NoError(t, err)
			require.Equal(t, test.enabled, strings.Contains(string(first), "var dag ="))
			internal, err := os.ReadFile(filepath.Join(root, "internal/dagger/dagger.gen.go"))
			require.NoError(t, err)
			require.NotContains(t, string(internal), "var dag")
			require.NoError(t, Generate(t.Context(), cfg))
			second, err := os.ReadFile(filepath.Join(root, "dagger.gen.go"))
			require.NoError(t, err)
			require.Equal(t, string(first), string(second))
			secondMod, err := os.ReadFile(filepath.Join(root, "go.mod"))
			require.NoError(t, err)
			require.Equal(t, string(firstMod), string(secondMod), "regeneration changed go.mod")
			for function, arg := range map[string]string{"Use": "decoded interface", "Echo": "decoded core object"} {
				cmd := exec.CommandContext(t.Context(), "go", "run", "-buildvcs=false", "./cmd/hello-dispatch", "engine-call")
				cmd.Dir = root
				cmd.Stdin = strings.NewReader(`{"receiverType":"Hello","receiverValue":{},"fnName":"` + function + `","fnArgs":{"value":"fixture-id"}}`)
				out, err := cmd.CombinedOutput()
				require.NoError(t, err, string(out))
				require.JSONEq(t, `"`+arg+`"`, strings.TrimSpace(string(out)))
			}
			original, err := os.ReadFile(filepath.Join(root, "main.go"))
			require.NoError(t, err)
			require.Equal(t, source, string(original))
		})
	}
}

func TestGlobalClientRemovalPreservesAuthorOnFailure(t *testing.T) {
	sdk := os.Getenv("GO_SDK_TEST_RUNTIME")
	if sdk == "" {
		t.Skip("set GO_SDK_TEST_RUNTIME to the SDK split checkout")
	}
	root := t.TempDir()
	mod := "module example.com/hello\n\ngo 1.26\n\nrequire dagger.io/dagger v1.0.0-beta.15\nreplace dagger.io/dagger => " + sdk + "\n"
	require.NoError(t, os.WriteFile(filepath.Join(root, "go.mod"), []byte(mod), 0644))
	source := "package hello\nimport \"example.com/hello/internal/dagger\"\ntype Hello struct{}\nfunc (h *Hello) Container() *dagger.Container { return dag.Container() }\n"
	require.NoError(t, os.WriteFile(filepath.Join(root, "main.go"), []byte(source), 0644))
	legacyGenerated := "// Code generated by dagger. DO NOT EDIT.\npackage hello\nvar dag = dagger.Connect()\n"
	require.NoError(t, os.WriteFile(filepath.Join(root, "dagger.gen.go"), []byte(legacyGenerated), 0644))
	schema, err := filepath.Abs("../../../cmd/dagger-go-sdk-codegen/generator/gogenerator/testdata/core/schema.json")
	require.NoError(t, err)
	cfg := GenerateConfig{ModuleRoot: root, ModuleName: "hello", SchemaPath: schema, SchemaVersion: "v1.0.0-beta.15", UnifiedClient: true, GoImage: "golang:1.26-alpine"}
	err = Generate(t.Context(), cfg)
	require.ErrorContains(t, err, "undefined: dag")
	original, err := os.ReadFile(filepath.Join(root, "main.go"))
	require.NoError(t, err)
	require.Equal(t, source, string(original))
	unchangedMod, err := os.ReadFile(filepath.Join(root, "go.mod"))
	require.NoError(t, err)
	require.Equal(t, mod, string(unchangedMod))
	unchangedGenerated, err := os.ReadFile(filepath.Join(root, "dagger.gen.go"))
	require.NoError(t, err)
	require.Equal(t, legacyGenerated, string(unchangedGenerated))
	_, err = os.Stat(filepath.Join(root, generator.OwnershipFile))
	require.ErrorIs(t, err, os.ErrNotExist)
}
