package gogenerator

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"testing/fstest"

	"github.com/dagger/go-sdk/cmd/dagger-go-sdk-codegen/generator"
	"github.com/stretchr/testify/require"
)

func TestResolveGlobalClientMigration(t *testing.T) {
	for _, test := range []struct {
		name, path, contents, policy string
		persisted                    *bool
		want                         bool
	}{
		{name: "fresh module"},
		{name: "generated legacy global", path: "dagger.gen.go", contents: "// Code generated by dagger. DO NOT EDIT.\npackage main\nvar dag = dagger.Connect()\n", want: true},
		{name: "handwritten file is not migration evidence", path: "dagger.gen.go", contents: "package main\nvar dag = customClient()\n"},
		{name: "comment mentioning dag is not evidence", path: "dagger.gen.go", contents: "// Code generated by dagger. DO NOT EDIT.\npackage main\n// var dag was removed\n"},
		{name: "legacy SDK string", path: "dagger.json", contents: `{"sdk":"go"}`, want: true},
		{name: "legacy SDK object", path: "dagger.json", contents: `{"sdk":{"source":"go"}}`, want: true},
		{name: "custom SDK", path: "dagger.json", contents: `{"sdk":{"source":"example.com/go"}}`},
		{name: "runtime manifest", path: "dagger-module.toml", contents: "name = 'hello'\n[runtime]\nsource = 'go'\n", want: true},
		{name: "runtime manifest comments", path: "dagger-module.toml", contents: "[runtime] # legacy\nsource = \"go\" # builtin\n", want: true},
		{name: "inline runtime manifest", path: "dagger-module.toml", contents: "runtime = { source = 'go' }\n", want: true},
		{name: "dotted runtime manifest", path: "dagger-module.toml", contents: "runtime.source = 'go'\n", want: true},
		{name: "quoted runtime manifest", path: "dagger-module.toml", contents: "['runtime']\n'source' = 'go'\n", want: true},
		{name: "custom runtime manifest", path: "dagger-module.toml", contents: "[runtime]\nsource = 'example.com/go'\n"},
		{name: "entrypoint manifest", path: "dagger-module.toml", contents: "[entrypoint]\nsource = 'go'\n"},
		{name: "explicit false wins", path: "dagger.json", contents: `{"sdk":"go"}`, policy: "false", persisted: boolPointer(true)},
		{name: "explicit true", policy: "true", persisted: boolPointer(false), want: true},
		{name: "persisted true", persisted: boolPointer(true), want: true},
		{name: "persisted false wins over old manifest", path: "dagger.json", contents: `{"sdk":"go"}`, persisted: boolPointer(false)},
	} {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			if test.path != "" {
				require.NoError(t, os.WriteFile(filepath.Join(root, test.path), []byte(test.contents), 0644))
			}
			ownership := generator.Ownership{}
			if test.persisted != nil {
				ownership.Compatibility = &generator.Compatibility{GlobalClient: test.persisted}
			}
			got, err := resolveGlobalClient(root, test.policy, ownership)
			require.NoError(t, err)
			require.Equal(t, test.want, got)
		})
	}
	_, err := resolveGlobalClient(t.TempDir(), "yes", generator.Ownership{})
	require.ErrorContains(t, err, "must be auto, true, or false")
	t.Run("malformed TOML fails before migration", func(t *testing.T) {
		root := t.TempDir()
		require.NoError(t, os.WriteFile(filepath.Join(root, "dagger-module.toml"), []byte("[runtime"), 0644))
		_, err := resolveGlobalClient(root, "auto", generator.Ownership{})
		require.ErrorContains(t, err, "read legacy Go manifest")
	})
}

func boolPointer(value bool) *bool { return &value }

func TestGlobalClientChoiceSurvivesPruning(t *testing.T) {
	for _, enabled := range []bool{false, true} {
		root := t.TempDir()
		overlay := fstest.MapFS{"dagger.gen.go": {Data: []byte("// Code generated by dagger. DO NOT EDIT.\npackage main\n")}}
		_, err := generator.WriteOwnedOverlayWithCompatibility(t.Context(), overlay, root, generator.Compatibility{GlobalClient: &enabled})
		require.NoError(t, err)
		require.NoError(t, generator.PruneOwnedClient(t.Context(), root))
		ownership, err := generator.ReadOwnership(root)
		require.NoError(t, err)
		got, err := resolveGlobalClient(root, "auto", ownership)
		require.NoError(t, err)
		require.Equal(t, enabled, got)
	}
}

// This covers package loading, generated decoders, the static dispatcher, and
// repeated generation rather than only checking a template's text.
func TestGenerateGlobalClientModes(t *testing.T) {
	sdk := os.Getenv("GO_SDK_TEST_RUNTIME")
	if sdk == "" {
		t.Skip("set GO_SDK_TEST_RUNTIME to the SDK split checkout")
	}
	schema, err := filepath.Abs("../../../cmd/dagger-go-sdk-codegen/generator/gogenerator/testdata/core/schema.json")
	require.NoError(t, err)
	for _, test := range []struct {
		name, policy, legacyFile, legacyContents string
		want                                     bool
		embedded                                 bool
	}{
		{name: "new module"},
		{name: "new embedded module", embedded: true},
		{name: "recognized generated module", legacyFile: "dagger.gen.go", legacyContents: "// Code generated by dagger. DO NOT EDIT.\npackage hello\nvar dag = dagger.Connect()\n", want: true},
		{name: "recognized legacy manifest", legacyFile: "dagger.json", legacyContents: `{"sdk":{"source":"go"}}`, want: true},
		{name: "explicit opt in", policy: "true", want: true},
		{name: "explicit opt out wins", policy: "false", legacyFile: "dagger.json", legacyContents: `{"sdk":"go"}`},
	} {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			mod := "module example.com/hello\n\ngo 1.26\n\nrequire dagger.io/dagger v1.0.0-beta.15\nreplace dagger.io/dagger => " + sdk + "\n"
			require.NoError(t, os.WriteFile(filepath.Join(root, "go.mod"), []byte(mod), 0644))
			source := `package hello
import (
 "context"
 "example.com/hello/internal/dagger"
)
type Hello struct{}
type Greeter interface {
 dagger.DaggerObject
 Greet(context.Context) (string, error)
}
func (h *Hello) Use(value Greeter) string { return "decoded interface" }
func (h *Hello) Echo(value *dagger.Container) string { return "decoded core object" }
`
			if test.want {
				source += "func (h *Hello) Legacy() *dagger.Container { return dag.Container() }\n"
			}
			require.NoError(t, os.WriteFile(filepath.Join(root, "main.go"), []byte(source), 0644))
			if test.legacyFile != "" {
				require.NoError(t, os.WriteFile(filepath.Join(root, test.legacyFile), []byte(test.legacyContents), 0644))
			}
			cfg := GenerateConfig{ModuleRoot: root, ModuleName: "hello", SchemaPath: schema, SchemaVersion: "v1.0.0-beta.15", UnifiedClient: !test.embedded, GoImage: "golang:1.26-alpine", GlobalClient: test.policy}
			require.NoError(t, Generate(t.Context(), cfg))
			first, err := os.ReadFile(filepath.Join(root, "dagger.gen.go"))
			require.NoError(t, err)
			require.Equal(t, test.want, strings.Contains(string(first), "var dag ="))
			internal, err := os.ReadFile(filepath.Join(root, "internal/dagger/dagger.gen.go"))
			require.NoError(t, err)
			require.NotContains(t, string(internal), "var dag")
			if test.legacyFile == "dagger.json" {
				require.NoError(t, os.Remove(filepath.Join(root, test.legacyFile)))
			}
			cfg.GlobalClient = "auto"
			require.NoError(t, Generate(t.Context(), cfg))
			second, err := os.ReadFile(filepath.Join(root, "dagger.gen.go"))
			require.NoError(t, err)
			require.Equal(t, string(first), string(second))
			ownership, err := generator.ReadOwnership(root)
			require.NoError(t, err)
			require.Equal(t, boolPointer(test.want), ownership.Compatibility.GlobalClient)
			for function, arg := range map[string]string{"Use": "decoded interface", "Echo": "decoded core object"} {
				cmd := exec.CommandContext(t.Context(), "go", "run", "-buildvcs=false", "./cmd/hello-dispatch", "engine-call")
				cmd.Dir = root
				cmd.Stdin = strings.NewReader(`{"receiverType":"Hello","receiverValue":{},"fnName":"` + function + `","fnArgs":{"value":"fixture-id"}}`)
				out, err := cmd.CombinedOutput()
				require.NoError(t, err, string(out))
				require.JSONEq(t, `"`+arg+`"`, strings.TrimSpace(string(out)))
			}
			original, err := os.ReadFile(filepath.Join(root, "main.go"))
			require.NoError(t, err)
			require.Equal(t, source, string(original))
		})
	}
}

func TestGlobalClientOptOutPreservesAuthorOnFailure(t *testing.T) {
	sdk := os.Getenv("GO_SDK_TEST_RUNTIME")
	if sdk == "" {
		t.Skip("set GO_SDK_TEST_RUNTIME to the SDK split checkout")
	}
	root := t.TempDir()
	mod := "module example.com/hello\n\ngo 1.26\n\nrequire dagger.io/dagger v1.0.0-beta.15\nreplace dagger.io/dagger => " + sdk + "\n"
	require.NoError(t, os.WriteFile(filepath.Join(root, "go.mod"), []byte(mod), 0644))
	source := "package hello\nimport \"example.com/hello/internal/dagger\"\ntype Hello struct{}\nfunc (h *Hello) Container() *dagger.Container { return dag.Container() }\n"
	require.NoError(t, os.WriteFile(filepath.Join(root, "main.go"), []byte(source), 0644))
	legacyGenerated := "// Code generated by dagger. DO NOT EDIT.\npackage hello\nvar dag = dagger.Connect()\n"
	require.NoError(t, os.WriteFile(filepath.Join(root, "dagger.gen.go"), []byte(legacyGenerated), 0644))
	schema, err := filepath.Abs("../../../cmd/dagger-go-sdk-codegen/generator/gogenerator/testdata/core/schema.json")
	require.NoError(t, err)
	cfg := GenerateConfig{ModuleRoot: root, ModuleName: "hello", SchemaPath: schema, SchemaVersion: "v1.0.0-beta.15", UnifiedClient: true, GoImage: "golang:1.26-alpine", GlobalClient: "false"}
	err = Generate(t.Context(), cfg)
	require.ErrorContains(t, err, "undefined: dag")
	original, err := os.ReadFile(filepath.Join(root, "main.go"))
	require.NoError(t, err)
	require.Equal(t, source, string(original))
	unchangedMod, err := os.ReadFile(filepath.Join(root, "go.mod"))
	require.NoError(t, err)
	require.Equal(t, mod, string(unchangedMod))
	unchangedGenerated, err := os.ReadFile(filepath.Join(root, "dagger.gen.go"))
	require.NoError(t, err)
	require.Equal(t, legacyGenerated, string(unchangedGenerated))
	_, err = os.Stat(filepath.Join(root, generator.OwnershipFile))
	require.ErrorIs(t, err, os.ErrNotExist)
}
