package templates

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"

	"github.com/dagger/go-sdk/cmd/dagger-go-sdk-codegen/generator"
	"github.com/dagger/go-sdk/cmd/dagger-go-sdk-codegen/introspection"
)

// GenerateCoreJSONCodecs lets shared core handles decode the ID strings the
// engine passes to module functions. Constructing a decoded handle stays lazy.
func GenerateCoreJSONCodecs(schema *introspection.Schema, schemaVersion string) ([]byte, error) {
	funcs := goTemplateFuncs{CommonFunctions: generator.NewCommonFunctions(schemaVersion, &FormatTypeFunc{})}
	types := map[string]string{}
	for _, typ := range schema.Types {
		if typ.Kind != introspection.TypeKindObject && typ.Kind != introspection.TypeKindInterface {
			continue
		}
		for _, field := range typ.Fields {
			if field.Name != "id" {
				continue
			}
			name := formatName(typ.Name)
			if typ.Kind == introspection.TypeKindInterface {
				name = funcs.interfaceClientName(typ.Name)
			}
			types[name] = typ.Name
		}
	}
	names := make([]string, 0, len(types))
	for name := range types {
		names = append(names, name)
	}
	sort.Strings(names)
	var source bytes.Buffer
	source.WriteString(`// Code generated by dagger. DO NOT EDIT.

package core

import (
 "context"
 "encoding/json"
)

// SetMarshalContext supplies the current module call context to handle codecs.
func SetMarshalContext(ctx context.Context) { marshalCtx = ctx }

`)
	for _, name := range names {
		fmt.Fprintf(&source, `func (r *%s) UnmarshalJSON(data []byte) error {
 var id string
 if err := json.Unmarshal(data, &id); err != nil { return err }
 *r = %s{query: selectNode(initRoot().QueryBuilder(), id, %q)}
 return nil
}

`, name, name, types[name])
	}
	return format.Source(source.Bytes())
}
