name = "engine-e2e"
engineVersion = "v1.0.0"

[runtime]
source = "dang"

[[dependencies]]
name = "engine-dev"
source = "github.com/dagger/dagger/.dagger/modules/engine-dev@f350d7bcee8633d3046e645ca9a820c0baa3d9c8"

[[dependencies]]
name = "runtime-floor-engine-dev"
source = "github.com/dagger/dagger/.dagger/modules/engine-dev@4932411ff7a9b0771dd53779d9a085406cefb531"

[[dependencies]]
name = "entrypoint-floor-engine-dev"
source = "github.com/dagger/dagger/.dagger/modules/engine-dev@2d95ef98b6824c5aaca4a43eb172c9a057c18619"
