name = "engine-e2e"
engineVersion = "v1.0.0"

[runtime]
source = "dang"

[[dependencies]]
name = "engine-dev"
source = "github.com/dagger/dagger/.dagger/modules/engine-dev@195b09187512b7e114f47048c773310701af87a7"
