package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dagger/go-sdk/cmd/dagger-go-sdk-codegen/introspection"
	"github.com/stretchr/testify/require"
)

const capturedRepo = "https://github.com/grouville/dagger"
const capturedPin = "34731d308d2c145e42161eba8078959c368efec0"

func TestNormalizeGeneratedSourceLinksCapturedBeta15(t *testing.T) {
	data, err := os.ReadFile("testdata/source-links/schema.json")
	require.NoError(t, err)
	var response introspection.Response
	require.NoError(t, json.Unmarshal(data, &response))
	anchor, err := workspaceSourceLinkAnchor(capturedRepo, capturedPin)
	require.NoError(t, err)
	git, err := os.ReadFile("testdata/source-links/git.go.txt")
	require.NoError(t, err)
	directory, err := os.ReadFile("testdata/source-links/directory.go.txt")
	require.NoError(t, err)
	catalog := newSourceLinkCatalog(response.Schema, response.SchemaVersion)
	result, err := normalizeGeneratedSourceLinks("go.gen.go", git, catalog, anchor, "../../../../..")
	require.NoError(t, err)
	require.Equal(t, string(directory), string(result))
	// The method and required argument both link to line 643, but the method
	// must retain column 1, not the argument's column 57.
	require.Contains(t, string(result), "main.go:643:1)")
	require.Contains(t, string(result), "main.go:384:2)")
	again, err := normalizeGeneratedSourceLinks("go.gen.go", result, catalog, anchor, "../../../../..")
	require.NoError(t, err)
	require.Equal(t, result, again)
}

func sourceLinkDirective(module, filename string, line, column int, link string) introspection.Directives {
	values := map[string]any{"module": module, "filename": filename, "line": line, "column": column, "url": link}
	directive := &introspection.Directive{Name: "sourceMap"}
	for name, value := range values {
		encoded, _ := json.Marshal(value)
		text := string(encoded)
		directive.Args = append(directive.Args, &introspection.DirectiveArg{Name: name, Value: &text})
	}
	return introspection.Directives{directive}
}

func TestNormalizeGeneratedSourceLinksOwnership(t *testing.T) {
	anchor, err := workspaceSourceLinkAnchor(capturedRepo, capturedPin)
	require.NoError(t, err)
	owned := anchor + "src/main.go#L10"
	external := "https://github.com/elsewhere/module/tree/" + capturedPin + "/main.go#L10"
	otherPin := capturedRepo + "/tree/other/main.go#L10"
	pinPrefix := capturedRepo + "/tree/" + capturedPin + "extra/main.go#L10"
	schema := &introspection.Schema{Types: introspection.Types{{
		Kind: introspection.TypeKindObject, Name: "Fixture",
		Directives: sourceLinkDirective("fixture", "src/main.go", 10, 6, owned),
		Fields: []*introspection.Field{
			{Name: "owned", Directives: sourceLinkDirective("fixture", "src/main.go", 10, 1, owned)},
			{Name: "external", Directives: sourceLinkDirective("external", "main.go", 10, 1, external)},
			{Name: "otherPin", Directives: sourceLinkDirective("fixture", "main.go", 10, 1, otherPin)},
			{Name: "pinPrefix", Directives: sourceLinkDirective("fixture", "main.go", 10, 1, pinPrefix)},
			{Name: "urlOnly", Directives: sourceLinkDirective("fixture", "", 10, 1, owned)},
		},
	}}}
	data := "// Code generated by dagger. DO NOT EDIT.\npackage fixture\n" +
		"type Fixture struct {} // fixture (" + owned + ")\n" +
		"func (r *Fixture) Owned() { // fixture (" + owned + ")\n" +
		"_ = `// fixture (" + owned + ")`\n" +
		"// fixture (" + owned + ")\n}\n" +
		"func (r *Fixture) External() { // external (" + external + ")\n}\n" +
		"func (r *Fixture) OtherPin() { // fixture (" + otherPin + ")\n}\n" +
		"func (r *Fixture) PinPrefix() { // fixture (" + pinPrefix + ")\n}\n" +
		"func (r *Fixture) URLOnly() { // fixture (" + owned + ")\n}\n"
	catalog := newSourceLinkCatalog(schema, "v1.0.0")
	result, err := normalizeGeneratedSourceLinks("fixture.go", []byte(data), catalog, anchor, "../../..")
	require.NoError(t, err)
	expected := strings.Replace(data, "type Fixture struct {} // fixture ("+owned+")", "type Fixture struct {} // fixture (../../../src/main.go:10:6)", 1)
	expected = strings.Replace(expected, "func (r *Fixture) Owned() { // fixture ("+owned+")", "func (r *Fixture) Owned() { // fixture (../../../src/main.go:10:1)", 1)
	require.Equal(t, expected, string(result))
	userCode := strings.TrimPrefix(data, "// Code generated by dagger. DO NOT EDIT.\n")
	result, err = normalizeGeneratedSourceLinks("main.go", []byte(userCode), catalog, anchor, "../../..")
	require.NoError(t, err)
	require.Equal(t, userCode, string(result))
}

func TestWorkspaceSourceLinkAnchor(t *testing.T) {
	for _, test := range []struct{ repo, anchor string }{
		{"https://github.com/org/repo", "https://github.com/org/repo/tree/pin/"},
		{"https://github.com/org/repo.git", "https://github.com/org/repo.git/tree/pin/"},
		{"ssh://git@github.com/org/repo.git", "ssh://git@github.com/org/repo.git/tree/pin/"},
		{"https://gitlab.com/org/repo", "https://gitlab.com/org/repo/tree/pin/"},
		{"https://dev.azure.com/org/project/_git/repo", "https://dev.azure.com/org/project/_git/repo/commit/pin?path=/"},
		{"https://bitbucket.org/org/repo", "https://bitbucket.org/org/repo/src/pin/"},
		{"git@github.com:org/repo.git", ""},
	} {
		t.Run(test.repo, func(t *testing.T) {
			anchor, err := workspaceSourceLinkAnchor(test.repo, "pin")
			require.NoError(t, err)
			require.Equal(t, test.anchor, anchor)
		})
	}
}

func TestNormalizeGeneratedSourceLinksQueryReceivers(t *testing.T) {
	anchor, err := workspaceSourceLinkAnchor(capturedRepo, capturedPin)
	require.NoError(t, err)
	link := anchor + "main.go#L10"
	schema := &introspection.Schema{Types: introspection.Types{{
		Kind: introspection.TypeKindObject, Name: "Query",
		Fields: []*introspection.Field{{Name: "fixture", Directives: sourceLinkDirective("fixture", "main.go", 10, 1, link)}},
	}}}
	data := "// Code generated by dagger. DO NOT EDIT.\npackage fixture\n" +
		"func (r *Query) Fixture() { // fixture (" + link + ")\n}\n" +
		"func (r *Client) Fixture() { // fixture (" + link + ")\n}\n"
	result, err := normalizeGeneratedSourceLinks("fixture.go", []byte(data), newSourceLinkCatalog(schema, "v1.0.0"), anchor, "../..")
	require.NoError(t, err)
	require.Equal(t, strings.ReplaceAll(data, link, "../../main.go:10:1"), string(result))
}

func TestNormalizeGeneratedSourceLinksEnumInitialism(t *testing.T) {
	anchor, err := workspaceSourceLinkAnchor(capturedRepo, capturedPin)
	require.NoError(t, err)
	link := anchor + "src/main.go#L10"
	schema := &introspection.Schema{Types: introspection.Types{{
		Kind: introspection.TypeKindEnum, Name: "ProtocolId",
		Directives: sourceLinkDirective("fixture", "src/main.go", 10, 6, link),
	}}}
	data := "// Code generated by dagger. DO NOT EDIT.\npackage fixture\n" +
		"type ProtocolId string // fixture (" + link + ")\n"
	result, err := normalizeGeneratedSourceLinks("fixture.go", []byte(data), newSourceLinkCatalog(schema, "v1.0.0"), anchor, "../../..")
	require.NoError(t, err)
	require.Equal(t, "// Code generated by dagger. DO NOT EDIT.\npackage fixture\ntype ProtocolId string // fixture (../../../src/main.go:10:6)\n", string(result))
}

func TestNormalizeGeneratedSourceLinksEnumCaseAliases(t *testing.T) {
	anchor, err := workspaceSourceLinkAnchor(capturedRepo, capturedPin)
	require.NoError(t, err)
	firstLink := anchor + "src/main.go#L10"
	secondLink := anchor + "src/main.go#L20"
	first := sourceLinkDirective("fixture", "src/main.go", 10, 2, firstLink)
	second := sourceLinkDirective("fixture", "src/main.go", 20, 2, secondLink)
	value := `"one"`
	for _, directives := range []*introspection.Directives{&first, &second} {
		*directives = append(*directives, &introspection.Directive{Name: "enumValue", Args: []*introspection.DirectiveArg{{Name: "value", Value: &value}}})
	}
	schema := &introspection.Schema{Types: introspection.Types{{
		Kind: introspection.TypeKindEnum, Name: "Choice",
		EnumValues: []introspection.EnumValue{{Name: "FIRST", Directives: first}, {Name: "first", Directives: second}},
	}}}
	data := "// Code generated by dagger. DO NOT EDIT.\npackage fixture\n" +
		"const ChoiceFirst Choice = \"one\" // fixture (" + firstLink + ")\n"
	result, err := normalizeGeneratedSourceLinks("fixture.go", []byte(data), newSourceLinkCatalog(schema, "v1.0.0"), anchor, "../../..")
	require.NoError(t, err)
	require.Equal(t, "// Code generated by dagger. DO NOT EDIT.\npackage fixture\nconst ChoiceFirst Choice = \"one\" // fixture (../../../src/main.go:10:2)\n", string(result))
}

func TestNormalizeSourceLinksCommandScope(t *testing.T) {
	output := t.TempDir()
	generated := filepath.Join(output, "src", "internal", "dagger", "go.gen.go")
	require.NoError(t, os.MkdirAll(filepath.Dir(generated), 0o755))
	git, err := os.ReadFile("testdata/source-links/git.go.txt")
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(generated, git, 0o640))
	require.NoError(t, runNormalizeSourceLinks([]string{
		"--introspection-json-path", "testdata/source-links/schema.json",
		"--output", output, "--scope", ".dagger/modules/cli",
		"--workspace-repo-url", capturedRepo, "--workspace-pin", capturedPin,
	}))
	result, err := os.ReadFile(generated)
	require.NoError(t, err)
	require.Contains(t, string(result), "../../../../../../.dagger/modules/go/main.go:643:1)")
	info, err := os.Stat(generated)
	require.NoError(t, err)
	require.Equal(t, os.FileMode(0o640), info.Mode().Perm())
}
